---
sudo: false
language: go
go:
  - 1.8
  - 1.9
  - 1.10
  - tip

branches:
  only:
    - master

install:
  - echo 'Installing dependencies ...'
  - go get -v
  - go get -v github.com/mitchellh/gox

script:
  - echo 'Building go artifacts for all platforms with gox ...'
  - gox -verbose -arch="amd64" -os="darwin linux windows" -output "dist/{{.OS}}_{{.Arch}}/{{.Dir}}" .

after_script:
  - echo 'Creating one archive per each platform ...'
  - zip -j packer-post-processor-vagrant-cloud-standalone_${TRAVIS_TAG}_darwin_amd64.zip ./dist/darwin_amd64/*
  - zip -j packer-post-processor-vagrant-cloud-standalone_${TRAVIS_TAG}_linux_amd64.zip ./dist/linux_amd64/*
  - zip -j packer-post-processor-vagrant-cloud-standalone_${TRAVIS_TAG}_windows_amd64.zip ./dist/windows_amd64/*
