---
sudo: false
language: go
go:
  - 1.8
  - 1.9
  - "1.10"
  - tip

branches:
  only:
    - master
    # build on tag
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

install:
  - echo 'Installing dependencies ...'
  - go get -v
  - go get -v github.com/mitchellh/gox

script:
  # Running tests ...
  - go test -v
  # Building go artifacts for all platforms with gox ...
  - gox -verbose -arch="amd64" -os="darwin linux windows" -output "dist/{{.OS}}_{{.Arch}}/{{.Dir}}" .

before_deploy:
  - echo 'Creating one archive per each platform ...'
  - zip -j packer-post-processor-vagrant-cloud-standalone_darwin_amd64.zip ./dist/darwin_amd64/*
  - zip -j packer-post-processor-vagrant-cloud-standalone_linux_amd64.zip ./dist/linux_amd64/*
  - zip -j packer-post-processor-vagrant-cloud-standalone_windows_amd64.zip ./dist/windows_amd64/*

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: Gg6cjwGoRbxBlGgtRXbwjZUX0MWwbHDuKS2jnXKHZOnxtae+0z8g11SzHnQnooHodzYMBp6JxzxcULjmRaxO0ZL4xqMM+wibgWYcATrYqx+PcqAsdKRQHBT12Sh6AhdQI59Mnvkt4+kP4OaN06DWsIi/zQ3RWzE9Yhe+AE4zBpibUGTCZKMyD/wojuo0bRjki5pVopvx9AxrjGcfgXjtYW8GDUWzgkY3QQXDZ0Xd8MeHV/V3UuB9t8UbuiMTOModSdq/OyrExtQ1lo4UUmMta8HoZi+kXSbucosUH9Jtmj0ZgqfqLm2uqiFZ+MGOjJbuHsPvaJWbqfMlRdLY5Ah2giPJGsxOCG569zb4z+yiC8OLMoMfvdMbp8x1UG9EIcixuq0zmRStIIdjZ6qudC1Z4Gr8XW4p7byInnA9+IR/cjx7QZSGMDgWmZ+kdTFk3sahSCrn8MGPpks6aPwhJBF4HFJP0ELhJB5CAe8J+UDHjSJ5YxGnFyYnHJ5QCVyswJJFCd2U8QZUP9nucAQ2688GUjj3BBWSJkWDS2/6Rbalvuh0iUMCRbF2gMq+XKMZGkO8gxmklIZE/zNGQLi/Nj3Fvbj5IAImW0uowSaJ5ulrqb5X/Yqpk30OqsAOdeQfgFaIHexcgs+BmVHNSKtPZzjgY/nnDHNTJeIiWRRLMxNGpEI=
  file: *.zip
  on:
    repo: armab/packer-post-processor-vagrant-cloud-standalone
    tags: true
